version: "2.1"
services:
  work:
    extends:
      file: common.yml
      service: deby

  build_test:
    extends:
      file: common.yml
      service: deby
    environment:
      TEST_TARGETS: ${TEST_TARGETS:-core-image-minimal}
      TEST_DISTROS: ${TEST_DISTROS:-deby-tiny}
      TEST_MACHINES: ${TEST_MACHINES:-qemux86}
    command: /home/deby/poky/meta-debian/tests/build_test.sh

  ptest:
    extends:
      file: common.yml
      service: deby
    environment:
      TEST_TARGETS: ${TEST_TARGETS}
      TEST_MACHINES: ${TEST_MACHINES:-qemux86}
    command: /home/deby/poky/meta-debian/tests/run_ptest.sh

volumes:
  downloads:
